name: askalgo-py
channels:
  - defaults
dependencies:
  - altair=4.1.0=py_1
  - attrs=20.2.0=py_0
  - blas=1.0=mkl
  - bokeh=2.2.1=py37_0
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py37_0
  - cycler=0.10.0=py37_0
  - entrypoints=0.3=py37_0
  - freetype=2.10.2=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.2=254
  - ipython_genutils=0.2.0=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py37_1
  - jupyter_core=4.6.3=py37_0
  - kiwisolver=1.2.0=py37h74a9793_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.2=h62dcd97_1
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37hba9282a_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.2.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - nbformat=5.0.7=py_0
  - numpy=1.19.1=py37h5510c5b_0
  - numpy-base=1.19.1=py37ha3acd2a_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=py_0
  - pandas=1.1.3=py37ha925a31_0
  - pillow=7.2.0=py37hcc1f983_0
  - pip=20.2.3=py37_0
  - plotly=4.11.0=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.17.3=py37he774522_0
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37he774522_1
  - qt=5.9.7=vc14h73c81de_0
  - retrying=1.3.3=py37_2
  - scipy=1.5.2=py37h9439919_0
  - seaborn=0.11.0=py_0
  - setuptools=50.3.0=py37h9490d1a_1
  - sip=4.19.8=py37h6538335_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - tk=8.6.10=he774522_0
  - toolz=0.11.1=py_0
  - tornado=6.0.4=py37he774522_1
  - traitlets=5.0.4=py_0
  - typing_extensions=3.7.4.3=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py37_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - backcall==0.2.0
    - colorama==0.4.3
    - decorator==4.4.2
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jupyter-client==6.1.7
    - parso==0.7.1
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.7
    - pygments==2.7.1
    - pywin32==228
    - pyzmq==19.0.2
    - wcwidth==0.2.5
prefix: C:\Users\tomyt\anaconda3\envs\askalgo-py

